---
- name: Copy multiple files
  hosts: localhost
  become: yes

  vars:
    file_list:
      - { src: '/opt/folder.yml', dest: '/opt/ansible/' }
      - { src: '/opt/copy.yml', dest: '/opt/ansible/' }

  tasks:
    - name: Copy files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop: "{{ file_list }}"

